app2/urls.py
from app2.views import *
from django.urls import path

app_name='app2'
urlpatterns=[
    path('second/',second,name='second'),
]

app3/urls.py
from app3.views import *
from django.urls import path

app_name='app3'

urlpatterns=[
    path('third/',third,name='third'),
]

project12/urls.py
from django.contrib import admin
from django.urls import path,include
from app1.views import *
import app2,app3

urlpatterns = [
    path("admin/", admin.site.urls),
    path('first/',first,name='first'),
    path('app2/',include('app2.urls')),
    path('app3/',include('app3.urls')),
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app3/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.
def first(request):
    return render(request,'first.html')

app2/views.py
from django.shortcuts import render

# Create your views here.
def second(request):
    return render(request,'second.html')

app3/views.py
from django.shortcuts import render

# Create your views here.
def third(request):
    return render(request,'third.html')

templates/first.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=<device-width>, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>JSPIDERS</h1>
        <h1><a href="{% url 'app2:second' %}">hi...</a></h1>
        <h1><a href="{% url 'app3:third' %}">hi...</a></h1>
    </center>
</body>
</html>

templates/second.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=<device-width>, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>sai</h1>
        <h1><a href="{% url 'first' %}">hi...</a></h1>
        <h1><a href="{% url 'app3:third' %} ">hi...</a></h1>
    </center>
</body>
</html>

templates/third.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=<device-width>, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>chandu</h1>
    <h1><a href="{% url 'app2:second' %}">hi...</a></h1>
    <h1><a href="{% url 'first' %}">hi...</a></h1>
</body>
</html>